-- Updated scripts for Milestone 2, 3 and 4. 
-- Team 05
-- Amal Mohamed and Linh Nguyen
-- 11 Jun 2018
-- Cssql/Putty/MySQL workbench


-- All table names are pluralized where possible 
-- Because some particular name without plurals is highlighted by 
-- MySQL workbench and I didn't want to risk the compiler mistakes
-- it for something else 


-- Drop scripts 
SET foreign_key_checks = 0; 
DROP TABLE IF EXISTS MULTI_RACES, MULTI_APPS, APPLICANT_TYPES, COLLEGES, DEGREES, MAJORS, MILITARY_BRANCH, 
RACES, STATES,TERMS, VETERAN_STATUS, TESTS, GENDERS,APPLICATIONS, APPLICATION_INFO, PERSONAL_INFO, EMPLOYMENT_HIST, EDU_HIST, STUDENT_TEST, USERS;
SET foreign_key_checks = 1; 

-- Re-populate table
CREATE TABLE GENDERS(
	GENDER_CODE CHAR(1) NOT NULL UNIQUE,
	GENDER_TYPE VARCHAR(30) NOT NULL,
	PRIMARY KEY (GENDER_CODE)
	) ENGINE = InnoDB;

DELETE FROM GENDERS; 
INSERT INTO GENDERS VALUE ('1', 'Female');
INSERT INTO GENDERS VALUE ('2','Male');
INSERT INTO GENDERS VALUE ('3', 'Non-Binary/Genderfluid');
INSERT INTO GENDERS VALUE ('4', 'Prefer Not to Answer');


-- There are more adjustment scripts for some table at the end!

CREATE TABLE STATES(
	STATE_CODE CHAR(2) PRIMARY KEY NOT NULL UNIQUE, 
	STATE_NAME VARCHAR(35) NOT NULL
) ENGINE = InnoDB; 


CREATE TABLE APPLICANT_TYPES(
	TYPE_CODE CHAR (1) NOT NULL UNIQUE, 
	GRAD_TYPE_NAME VARCHAR (30) NOT NULL,
	PRIMARY KEY (TYPE_CODE)
) ENGINE = InnoDB;

CREATE TABLE TERMS(
	TERM_CODE CHAR(2) NOT NULL UNIQUE,
	TERM_QUAR VARCHAR(40) NOT NULL, 
	TERM_YEAR INT(4) NOT NULL, 
	PRIMARY KEY (TERM_CODE)
) ENGINE = InnoDB;


CREATE TABLE MAJORS(
	MAJOR_CODE CHAR(3) NOT NULL UNIQUE, 
	MAJOR_NAME VARCHAR (55) NOT NULL, 
	PRIMARY KEY (MAJOR_CODE)
) ENGINE = InnoDB;

CREATE TABLE DEGREES( 
	DEGREE_CODE CHAR(1) NOT NULL UNIQUE, 
	DEGREE_TYPE VARCHAR (20) NOT NULL,
	PRIMARY KEY (DEGREE_CODE) 
) ENGINE = InnoDB;

CREATE TABLE COLLEGES( 
	COLL_CODE CHAR(3) NOT NULL UNIQUE, 
	COLL_NAME VARCHAR(45) NOT NULL, 
	PRIMARY KEY (COLL_CODE)
) ENGINE = InnoDB; 

CREATE TABLE TESTS(
	TEST_ID CHAR(3) NOT NULL UNIQUE, 
	TEST_NAME VARCHAR(25) NOT NULL, 
	PRIMARY KEY (TEST_ID)
) ENGINE = InnoDB; 

CREATE TABLE VETERAN_STATUS( 
	VET_CODE CHAR(1) NOT NULL UNIQUE, 
	VET_TYPE VARCHAR(20) NOT NULL, 
	PRIMARY KEY (VET_CODE)
) ENGINE = InnoDB;


CREATE TABLE RACES( 
	RACE_CODE CHAR(2) NOT NULL UNIQUE, 
	RACE VARCHAR(40) NOT NULL, 
	PRIMARY KEY (RACE_CODE)
) ENGINE = InnoDB; 


CREATE TABLE MILITARY_BRANCH( 
	BRANCH_CODE CHAR(1) NOT NULL UNIQUE, 
	BRANCH_TYPE VARCHAR(15) NOT NULL,
	PRIMARY KEY (BRANCH_CODE)
 ) ENGINE = InnoDB; 


CREATE TABLE APPLICATIONS( 
	APP_ID INT NOT NULL AUTO_INCREMENT, 
	TYPE_CODE CHAR (1) NOT NULL, 
	TERM_CODE CHAR (2) NOT NULL, 
	MAJOR_CODE CHAR (3) NOT NULL,
	DEGREE_CODE CHAR (1) NOT NULL, 
	COLL_CODE CHAR(3) NOT NULL,
	PRIMARY KEY (APP_ID),
	FOREIGN KEY (TYPE_CODE) REFERENCES APPLICANT_TYPES(TYPE_CODE),
	FOREIGN KEY (TERM_CODE) REFERENCES TERMS(TERM_CODE),
	FOREIGN KEY (MAJOR_CODE) REFERENCES MAJORS(MAJOR_CODE),
	FOREIGN KEY (DEGREE_CODE) REFERENCES DEGREES(DEGREE_CODE),
	FOREIGN KEY (COLL_CODE) REFERENCES COLLEGES(COLL_CODE)
) ENGINE = InnoDB;

CREATE TABLE PERSONAL_INFO( 	
	PERS_ID INT NOT NULL AUTO_INCREMENT, 
	APP_ID INT NOT NULL, 
	FIRST_NAME VARCHAR (25) NOT NULL, 
	MID_INITIAL VARCHAR (4), 
	LAST_NAME VARCHAR (30) NOT NULL, 
	DOB DATE NOT NULL, 
	PHONE_AREA CHAR(3) NOT NULL, 
	PHONE_NUM  CHAR(7) NOT NULL, 
	GENDER CHAR(1) NOT NULL, 
	MAIL_ADDRESS VARCHAR(40) NOT NULL, 
	ADDRESS_CITY VARCHAR(10) NOT NULL, 
	ZIPCODE CHAR(5) NOT NULL,
	STATE_CODE CHAR(2) NOT NULL, 
	HISPANIC CHAR(1) NOT NULL, 
	US_NATIVE CHAR(1) NOT NULL, 
	CITIZEN CHAR(1) NOT NULL,
	RACE_CODE CHAR(2) NOT NULL, 
	VET_CODE CHAR(1) NOT NULL, 
	BRANCH_CODE CHAR(1), 
	PRIMARY KEY (PERS_ID),
	FOREIGN KEY (STATE_CODE) REFERENCES STATES(STATE_CODE), 
	FOREIGN KEY (VET_CODE) REFERENCES VETERAN_STATUS(VET_CODE),
	FOREIGN KEY (BRANCH_CODE) REFERENCES MILITARY_BRANCH(BRANCH_CODE),
	FOREIGN KEY (RACE_CODE) REFERENCES RACES(RACE_CODE),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS(APP_ID)
)  ENGINE = InnoDB; 

CREATE TABLE APPLICATION_INFO(
	APP_INFO_ID INT NOT NULL AUTO_INCREMENT, 
	FIN_AID CHAR(1) NOT NULL, 
	TUIT_ASSIST CHAR(1) NOT NULL, 
	ADD_PROG CHAR(1) NOT NULL, 
	PROBATION_HIST CHAR(1) NOT NULL, 
	APP_ID INT NOT NULL, 
	FELONY CHAR(1) NOT NULL, 
	PRIMARY KEY (APP_INFO_ID), 
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS(APP_ID)
) ENGINE = InnoDB; 
CREATE TABLE EMPLOYMENT_HIST( 
	EMP_ID INT NOT NULL AUTO_INCREMENT, 
	APP_ID INT NOT NULL, 
	JOB_START_MONTH INT(2) NOT NULL, 
	JOB_END_MONTH INT(2),
	JOB_START_YEAR INT(4) NOT NULL, 
	JOB_END_YEAR INT(4),
	EMP_NAME VARCHAR(25) NOT NULL, 
	EMP_ADDRESS VARCHAR(40) NOT NULL, 
	EMP_CITY VARCHAR(10) NOT NULL,
	EMP_ZIPCODE VARCHAR(5) NOT NULL,
	PART_FULL ENUM ('Yes','No') NOT NULL, 
	IS_CURRENT ENUM ('Yes', 'No') NOT NULL,
	TITLE VARCHAR(35) NOT NULL, 
	PHONE_AREA CHAR(3), 
	PHONE_NUM  CHAR(7),
	PRIMARY KEY (EMP_ID),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS(APP_ID)
)  ENGINE = InnoDB; 

DROP TABLE IF EXISTS EDU_HIST;

CREATE TABLE EDU_HIST( 
	ED_ID INT NOT NULL AUTO_INCREMENT, 
	APP_ID INT NOT NULL, 
	ED_START_MONTH INT(2) NOT NULL, 
	ED_START_YEAR INT(4) NOT NULL, 
	ED_END_MONTH INT(2) NOT NULL,
	ED_END_YEAR INT(4) NOT NULL, 
	ED_DEGREE VARCHAR(30) NOT NULL, 
	DEG_DATE_MONTH INT(2) NOT NULL, 
	DEG_DATE_YEAR INT(4) NOT NULL,
	INSTI_NAME VARCHAR(30) NOT NULL, 
	MAJOR VARCHAR(30) NOT NULL,
	PHONE_AREA CHAR(3), 
	PHONE_NUM  CHAR(7),
	PRIMARY KEY (ED_ID),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS(APP_ID)
) ENGINE = InnoDB; 
	


CREATE TABLE STUDENT_TEST(
	STU_TEST_ID INT NOT NULL AUTO_INCREMENT, 
	APP_ID INT NOT NULL, 
	TEST_ID CHAR(3) NOT NULL,
	SCORE INT NOT NULL, 
	MONTH_TAKEN INT(2) NOT NULL,
	YEAR_TAKEN INT(4) NOT NULL,
	PRIMARY KEY (STU_TEST_ID),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS(APP_ID),
	FOREIGN KEY (TEST_ID) REFERENCES TESTS(TEST_ID)
) ENGINE = InnoDB;

-- This is for Milestone 4
-- User table with username and password
-- There will be relationship between users and applications (linking table)
CREATE TABLE USERS ( 
	USER_ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(15) NOT NULL UNIQUE, 
	PASSWORD VARCHAR(10) NOT NULL, 
	APP_ID INT, 
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS(APP_ID)
	) ENGINE = InnoDB; 

-- This is for Milestone 2
-- Linking table between races and applications 
-- However I could not be able to extract forms from data and insert here

CREATE TABLE MULTI_RACES( 
	MULTI_ID INT NOT NULL AUTO_INCREMENT,
	APP_ID INT NOT NULL, 
	RACE_CODE CHAR(2) NOT NULL,
	PRIMARY KEY (MULTI_ID),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS (APP_ID),
	FOREIGN KEY (RACE_CODE) REFERENCES RACES(RACE_CODE)
) ENGINE = InnoDB;

-- Linking table between users and applications
CREATE TABLE MULTI_APPS( 
	MULTI_APP INT NOT NULL AUTO_INCREMENT, 
	APP_ID INT NOT NULL,
	USER_ID INT NOT NULL, 
	PRIMARY KEY (MULTI_APP),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS (APP_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE = InnoDB;

-- Insert into TERMS table

INSERT INTO TERMS VALUES('10','Spring quarter (March)','2018');
INSERT INTO TERMS VALUES('20','Winter quarter (December)','2018');
INSERT INTO TERMS VALUES('30','Fall quarter (September)','2018');
INSERT INTO TERMS VALUES('40','Summer quarter (June)','2018');
INSERT INTO TERMS VALUES('50','Spring quarter (March)','2018');
INSERT INTO TERMS VALUES('60','Winter quarter (December)','2019');
INSERT INTO TERMS VALUES('70','Fall quarter (September)','2019');

--Inserting data into APPLICANT_TYPES table--
INSERT INTO APPLICANT_TYPES VALUES('1','Graduate');
INSERT INTO APPLICANT_TYPES VALUES('2','Graduate Non-Matriculated');
INSERT INTO APPLICANT_TYPES VALUES('3','Graduate Readmission');

--Inserting data into DEGREES table--
INSERT INTO DEGREES VALUES('1','Certificates');
INSERT INTO DEGREES VALUES('2','Masters');
-- Inserting data into the RACES tables - 
INSERT INTO RACES VALUES('01','Asian');
INSERT INTO RACES VALUES('02','Black/African American');
INSERT INTO RACES VALUES('03','Native Hawaiian/Pacific Islander');
INSERT INTO RACES VALUES('04','Native American/Native Indian');
INSERT INTO RACES VALUES('05','White/Middle Eastern');

--Inserting data into VETERAN_STATUS table--
INSERT INTO VETERAN_STATUS VALUES('1','Not a veteran');
INSERT INTO VETERAN_STATUS VALUES('2','Currently serving');
INSERT INTO VETERAN_STATUS VALUES('3','Previously served');
INSERT INTO VETERAN_STATUS VALUES('4','Current dependent');

--Inserting data into MILITARY_BRANCH  table--
INSERT INTO MILITARY_BRANCH VALUES('1','Army');
INSERT INTO MILITARY_BRANCH VALUES('2','Marine Corp');
INSERT INTO MILITARY_BRANCH VALUES('3','Navy');
INSERT INTO MILITARY_BRANCH VALUES('4','Air Force');
INSERT INTO MILITARY_BRANCH VALUES('5','Coast Guard');

--Inserting data into MAJORS table--
INSERT INTO MAJORS VALUES('100','Certificate in Computer Science Fundamentals');
INSERT INTO MAJORS VALUES('201','Certificate in Software Architecture and Design');
INSERT INTO MAJORS VALUES('302','Certificate in Software Project Management');
INSERT INTO MAJORS VALUES('403','Master of Science in Computer Science');
INSERT INTO MAJORS VALUES('504','Master of Science in Mechanical Engineering');
INSERT INTO MAJORS VALUES('605','Master of Science in Structural Engineering');

--Inserting data into COLLEGES table--

INSERT INTO COLLEGES VALUES('100','College of Science and Engineering');
INSERT INTO COLLEGES VALUES('201','Albers School of Business');
INSERT INTO COLLEGES VALUES('302','College of Arts and Sciences');
INSERT INTO COLLEGES VALUES('403','College of Education');
INSERT INTO COLLEGES VALUES('504','College of Nursing');
INSERT INTO COLLEGES VALUES('605','School of Theology and Ministry');

--Inserting data into TESTS table--

INSERT INTO TESTS VALUES('100','CBEST');
INSERT INTO TESTS VALUES('200','GMAT');
INSERT INTO TESTS VALUES('300','GRE General');
INSERT INTO TESTS VALUES('400','IELTS');
INSERT INTO TESTS VALUES('500','MAT');
INSERT INTO TESTS VALUES('600','PRAXIS');
INSERT INTO TESTS VALUES('700','TOEFL');
INSERT INTO TESTS VALUES('800','WEST-B');
INSERT INTO TESTS VALUES('900','WEST-E');


----- 


-- Edited scripts for Milestone 3
-- Already changed table names so not needed 
--ALTER TABLE APPLICATIONS MODIFY COLUMN APP_ID INT NOT NULL AUTO_INCREMENT; 
--ALTER TABLE COLLEGE RENAME TO COLLEGES;
--ALTER TABLE MAJOR RENAME TO MAJORS; 
--ALTER TABLE STATE RENAME TO STATES; 
--ALTER TABLE APPLICANT_TYPE RENAME TO APPLICANT_TYPES;
-- ALTER TABLE RACE RENAME TO RACES;
-- ALTER TABLE TERM RENAME TO TERMS; 
-- ALTER TABLE TEST RENAME TO TESTS;


 

ALTER TABLE PERSONAL_INFO ADD CONSTRAINT FK_GENDER FOREIGN KEY (GENDER) REFERENCES GENDERS(GENDER_CODE); 

DROP TABLE EMPLOYMENT_HIST; 


-- job end can be null because it might be a current job 
CREATE TABLE EMPLOYMENT_HIST( 
	EMP_ID CHAR(8) NOT NULL UNIQUE, 
	APP_ID INT NOT NULL, 
	JOB_START_MONTH INT(2) NOT NULL, 
	JOB_END_MONTH INT(2),
	JOB_START_YEAR INT(4) NOT NULL, 
	JOB_END_YEAR INT(4),
	EMP_NAME VARCHAR(25) NOT NULL, 
	EMP_ADDRESS VARCHAR(40) NOT NULL, 
	EMP_CITY VARCHAR(10) NOT NULL,
	EMP_ZIPCODE VARCHAR(5) NOT NULL,
	PART_FULL ENUM ('Yes','No') NOT NULL, 
	IS_CURRENT ENUM ('Yes', 'No') NOT NULL,
	TITLE VARCHAR(35) NOT NULL, 
	PHONE_AREA CHAR(3), 
	PHONE_NUM  CHAR(7),
	PRIMARY KEY (EMP_ID),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS(APP_ID)
)  ENGINE = InnoDB; 

DROP TABLE EDU_HIST;

CREATE TABLE EDU_HIST( 
	ED_ID CHAR(8) NOT NULL UNIQUE, 
	APP_ID INT NOT NULL, 
	ED_START_MONTH INT(2) NOT NULL, 
	ED_START_YEAR INT(4) NOT NULL, 
	ED_END_MONTH INT(2) NOT NULL,
	ED_END_YEAR INT(4) NOT NULL, 
	ED_DEGREE VARCHAR(30) NOT NULL, 
	DEG_DATE_MONTH INT(2) NOT NULL, 
	DEG_DATE_YEAR INT(4) NOT NULL,
	INSTI_NAME VARCHAR(30) NOT NULL, 
	MAJOR VARCHAR(30) NOT NULL,
	PHONE_AREA CHAR(3), 
	PHONE_NUM  CHAR(7),
	PRIMARY KEY (ED_ID),
	FOREIGN KEY (APP_ID) REFERENCES APPLICATIONS(APP_ID)
) ENGINE = InnoDB; 

 


DELETE FROM STATES; 

INSERT INTO STATES VALUES ('AL', 'Alabama'),
('AK', 'Alaska'),
('AZ', 'Arizona'),
('AR', 'Arkansas'),
('CA', 'California'),
('CO', 'Colorado'),
('CT', 'Connecticut'),
('DE', 'Delaware'),
('DC', 'District of Columbia'),
('FL', 'Florida'),
('GA', 'Georgia'),
('HI', 'Hawaii'),
('ID', 'Idaho'),
('IL', 'Illinois'),
('IN', 'Indiana'),
('IA', 'Iowa'),
('KS', 'Kansas'),
('KY', 'Kentucky'),
('LA', 'Louisiana'),
('ME', 'Maine'),
('MD', 'Maryland'),
('MA', 'Massachusetts'),
('MI', 'Michigan'),
('MN', 'Minnesota'),
('MS', 'Mississippi'),
('MO', 'Missouri'),
('MT', 'Montana'),
('NE', 'Nebraska'),
('NV', 'Nevada'),
('NH', 'New Hampshire'),
('NJ', 'New Jersey'),
('NM', 'New Mexico'),
('NY', 'New York'),
('NC', 'North Carolina'),
('ND', 'North Dakota'),
('OH', 'Ohio'),
('OK', 'Oklahoma'),
('OR', 'Oregon'),
('PA', 'Pennsylvania'),
('PR', 'Puerto Rico'),
('RI', 'Rhode Island'),
('SC', 'South Carolina'),
('SD', 'South Dakota'),
('TN', 'Tennessee'),
('TX', 'Texas'),
('UT', 'Utah'),
('VT', 'Vermont'),
('VA', 'Virginia'),
('WA', 'Washington'),
('WV', 'West Virginia'),
('WI', 'Wisconsin'),
('WY', 'Wyoming');

-- Insert 1 admin account with bad password
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('admin','1234');

-- Adjustment scripts for some table
-- Changing all yes/no radio to ENUM type 
ALTER TABLE PERSONAL_INFO MODIFY COLUMN US_NATIVE ENUM ('Yes', 'No');
ALTER TABLE PERSONAL_INFO MODIFY COLUMN CITIZEN ENUM ('Yes', 'No');
ALTER TABLE PERSONAL_INFO MODIFY COLUMN HISPANIC ENUM ('Yes', 'No');

ALTER TABLE APPLICATION_INFO MODIFY COLUMN FIN_AID ENUM ('Yes', 'No');
ALTER TABLE  APPLICATION_INFO MODIFY COLUMN TUIT_ASSIST ENUM ('Yes', 'No');
ALTER TABLE  APPLICATION_INFO MODIFY COLUMN ADD_PROG ENUM ('Yes', 'No');
ALTER TABLE  APPLICATION_INFO MODIFY COLUMN PROBATION_HIST ENUM ('Yes', 'No');
ALTER TABLE  APPLICATION_INFO MODIFY COLUMN FELONY ENUM ('Yes', 'No');

-- Add reference to States table
ALTER TABLE EMPLOYMENT_HIST ADD STATE_CODE CHAR(2);
ALTER TABLE EMPLOYMENT_HIST ADD CONSTRAINT FK_STATE FOREIGN KEY (STATE_CODE) REFERENCES STATES(STATE_CODE);
